version: '3'
services:
  db:
    image: postgres
#  redis:
#    image: "redis:3.2.12"
#    ports:
#      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    tty: true
    environment:
      - public_ip=0.0.0.0
      - firebase_token=<dein token hier>
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/traveler
    ports:
      - "8000:8000"
    depends_on:
      - db