# Generated by Django 2.2.1 on 2019-11-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplication', '0002_auto_20191127_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplication',
            name='supplication_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplication.SupplicationData', verbose_name='Stammdaten'),
        ),
        migrations.CreateModel(
            name='SupplicationVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplication.Supplication', verbose_name='Parent')),
                ('supplication_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplication.SupplicationData', verbose_name='Stammdaten')),
            ],
        ),
    ]
