# Generated by Django 2.2.1 on 2019-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(null=True, verbose_name='Beschreibung')),
            ],
        ),
    ]
