# Generated by Django 2.2.1 on 2019-05-19 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0003_infobox_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoboxes', to='infobox.Category', verbose_name='Kategorie'),
        ),
    ]
