# Generated by Django 2.2.1 on 2019-05-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0004_auto_20190519_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='infobox.Category', verbose_name='Oberkategorie'),
        ),
    ]
