# Generated by Django 2.2.1 on 2019-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0005_auto_20190519_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='infobox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infobox.Category'),
        ),
    ]
