# Generated by Django 2.2.1 on 2019-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0007_auto_20190606_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='type',
            field=models.CharField(max_length=200, null=True, verbose_name='Typ'),
        ),
    ]
