# Generated by Django 2.2.1 on 2019-06-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0008_infobox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
