# Generated by Django 2.2.1 on 2019-06-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0009_auto_20190606_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infobox',
            old_name='infobox_parent',
            new_name='parent',
        ),
    ]
