# Generated by Django 2.2.1 on 2019-06-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0010_auto_20190606_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infobox.Infobox'),
        ),
    ]
