# Generated by Django 2.2.1 on 2019-06-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0011_auto_20190606_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='type',
            field=models.CharField(choices=[('Arabisch', 'Arabisch'), ('Deutsch', 'Deutsch'), ('Türkisch', 'Türkisch'), ('Urdu', 'Urdu')], max_length=200, null=True, verbose_name='Typ'),
        ),
    ]
