# Generated by Django 2.2.1 on 2019-06-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0012_auto_20190606_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infobox',
            old_name='type',
            new_name='language',
        ),
    ]
