# Generated by Django 2.2.1 on 2019-10-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0016_infobox_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='type',
            field=models.CharField(choices=[('Mustahabb', 'Mustahabb'), ('Sunnah', 'Sunnah')], max_length=200, null=True),
        ),
    ]
