# Generated by Django 2.2.1 on 2019-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0017_infobox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='type',
            field=models.CharField(blank=True, choices=[('Mustahabb', 'Mustahabb'), ('Sunnah', 'Sunnah')], max_length=200, null=True),
        ),
    ]
